apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-dev
  namespace: argocd
spec:
  description: Cluster resources for dev
  sourceRepos:
  - https://github.com/your-org/your-repo
  destinations:
  - namespace: "*"
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  namespaceResourceWhitelist:
  - group: "*"
    kind: "*"
