apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: infisical-readonly
  namespace: example
spec:
  provider: infisical
  parameters:
    projectSlug: example
    envSlug: dev
    secretsPath: /
    authSecretName: infisical-readonly-token
    authSecretNamespace: kube-system
    objects: |
      - objectName: EXAMPLE_SECRET
