apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: infisical-readonly
  namespace: example
spec:
  provider: infisical
  parameters:
    # Kubernetes auth requires an Infisical identityId configured for this cluster.
    authMethod: "kubernetes"
    infisicalUrl: "https://infisical.example.com"
    # caCertificate: |
    #   -----BEGIN CERTIFICATE-----
    #   REPLACE_ME
    #   -----END CERTIFICATE-----
    identityId: "REPLACE_ME"
    projectId: "REPLACE_ME"
    envSlug: "dev"
    useDefaultAudience: "false"
    secrets: |
      - secretPath: "/"
        fileName: "EXAMPLE_SECRET"
        secretKey: "EXAMPLE_SECRET"
